export const mix=n=>{n=Math.imul(n^n>>>16,0x7feb352d);n=Math.imul(n^n>>>15,0x846ca68b);return(n^n>>>16)>>>0};
export const R=s=>()=>((s=mix(s+0x9e3779b9))/2**32);
export const hex=n=>(n>>>0).toString(16).toUpperCase().padStart(8,0);
export const Hx=s=>parseInt((s||'').replace(/[^0-9a-f]/gi,''),16)>>>0||0x13c0ffee;
const clamp=(n,a,b)=>n<a?a:n>b?b:n;
export const EV={KILL:1,BIRTH:2,CHILD_KILL:3,WELL:4,BOSS:5};
export function laws(s){let r=R(mix(s^0x50524953));return{shape:r()*4|0,mut:r()*4|0,wet:r()*4|0,ruin:r()*4|0,agg:r()*4|0,magic:r()*4|0,bias:r()*7|0,sym:r()*4|0,eco:r()*4|0}}
export function region(seed,w,x,y){let s=mix(seed^Math.imul(x,73856093)^Math.imul(y,19349663)^0x52454749),r=R(s),shift=(r()*3|0)-1,b=(w.bias+shift+7)%7;let g={s,b,topo:(w.shape+(r()*4|0))&3,wet:clamp(w.wet+(r()*3|0)-1,0,3),ruin:clamp(w.ruin+(r()*3|0)-1,0,3),agg:clamp(w.agg+(r()*3|0)-1,0,3),magic:clamp(w.magic+(r()*3|0)-1,0,3),eco:(w.eco+(r()*4|0))&3,sym:(w.sym+(r()*4|0))&3,ops:[]};for(let i=0;i<6;i++)g.ops.push(1+(r()*15|0));return g}
export function tileAt(seed,w,sx,sy,x,y){let g=region(seed,w,sx,sy),q=mix(g.s^Math.imul(x,83492791)^Math.imul(y,2654435761)),n=q&255;if(g.topo==1)n^=(x*17+y*29)&255;if(g.topo==2)n=(n+((x^y)&1)*55)&255;if(g.topo==3)n=(n+Math.abs(x*13-y*19))&255;return{g,q,k:n<12+g.wet*8?1:n>244-g.ruin*6?2:0}}
export function speciesProgram(seed,w,sx,sy,i){let g=region(seed,w,sx,sy),s=mix(g.s^Math.imul(i+1,31337)^0x53504543),r=R(s),p=0;for(let n=0;n<6;n++){let op=g.ops[r()*g.ops.length|0];if(r()<w.mut*.07)op=1+(r()*15|0);p|=(op&15)<<(n*4)}return{seed:s,program:p>>>0,region:g,root:i,generation:0,branch:0}}
export function mutateProgram(p,s,pressure=1){let r=R(s),n=1+(pressure>1&&r()<pressure*.18?1:0);for(;n--;){let q=r()*6|0,o=1+(r()*15|0);p=(p&~(15<<(q*4)))|o<<(q*4)}return p>>>0}
export function descendantProgram(seed,w,sx,sy,root,generation=1,branch=0){let sp=speciesProgram(seed,w,sx,sy,root),p=sp.program,s=sp.seed;generation=clamp(generation|0,1,15);branch&=15;for(let n=1;n<=generation;n++){s=mix(s^Math.imul(n,0x45d9f3b)^Math.imul(branch+1,0x27d4eb2d)^0x4d555441);p=mutateProgram(p,s,w.mut);s=mix(s^p)}return{seed:s,program:p,region:sp.region,root,generation,branch}}
export function interpret(sp){let t={legs:2,horn:0,wing:0,shell:0,eye:0,size:1,speed:.72,behavior:0,shoot:0,phase:0};for(let n=0;n<6;n++){let o=sp.program>>>(n*4)&15;if(o==1||o==11)t.legs=Math.min(8,t.legs+2);if(o==2)t.horn=1;if(o==3)t.wing=1;if(o==4)t.shell=1;if(o==5)t.eye=1;if(o==6)t.size=Math.min(3,t.size+1);if(o==7)t.speed+=.18;if(o==8){t.horn=1;t.behavior=1}if(o==9){t.wing=1;t.behavior=2}if(o==10){t.eye=1;t.shoot=1;t.behavior=3}if(o==12)t.phase=1;if(o==13){t.shell=1;t.size=Math.min(3,t.size+1)}if(o==14){t.wing=1;t.speed+=.2}if(o==15)t.behavior=0}if(t.horn&&!t.behavior)t.behavior=1;if(t.wing&&t.behavior==0)t.behavior=2;return t}
export function materialize(sp){let t=interpret(sp),r=R(mix(sp.seed^sp.program^sp.generation));return{...t,g:sp.seed,program:sp.program,b:sp.region.b,root:sp.root,generation:sp.generation,branch:sp.branch,nameA:(sp.program>>>4)%12,nameB:(sp.program>>>16)%8,hp:1+t.size+(t.shell?2:0),x:18+r()*284,y:28+r()*134,vx:0,vy:0,t:0}}
export function species(seed,w,sx,sy,i){return materialize(speciesProgram(seed,w,sx,sy,i))}
export function descendant(seed,w,sx,sy,root,generation=1,branch=0){return materialize(descendantProgram(seed,w,sx,sy,root,generation,branch))}
export const population=(seed,w,sx,sy)=>{let g=region(seed,w,sx,sy);return 3+g.eco+(mix(g.s^0x504f50)&3)};
export function wellSites(seed){let a=[];for(let c=0;c<7;c++){let q=mix(seed^Math.imul(c+1,0x6d2b79f5)),x,y;do{q=mix(q^a.length);x=(q%9|0)-4;y=((q>>>8)%9|0)-4}while((!x&&!y)||a.some(v=>v.x==x&&v.y==y));a.push({x,y,c})}return a}
export function wellAt(seed,x,y){let a=wellSites(seed);for(let w of a)if(w.x==x&&w.y==y)return w.c;return-1}
export function threat(seed,w){let a=wellSites(seed),g=region(seed,w,0,0),s=mix(seed^0x54485254),p=0;for(let n=0;n<6;n++){let z=a[(n+(s&7))%7],q=region(seed,w,z.x,z.y),o=q.ops[mix(s^n)%q.ops.length];p|=(o&15)<<(n*4)}let m=materialize({seed:s,program:p>>>0,region:g,root:255,generation:15,branch:15});m.boss=1;m.size=4;m.hp=24+w.agg*4+w.magic*3;m.speed=.55+w.agg*.08;m.shoot=1;m.eye=1;m.behavior=1+(w.shape%3);m.x=160;m.y=62;return m}
export const event=(type,sx,sy,subject=0,data=0)=>((type&15)|((sx+32&63)<<4)|((sy+32&63)<<10)|((subject&255)<<16)|((data&255)<<24))>>>0;
export const unpack=e=>({type:e&15,sx:(e>>>4&63)-32,sy:(e>>>10&63)-32,subject:e>>>16&255,data:e>>>24&255});
export const canonLedger=a=>[...new Set(a.map(n=>n>>>0))].sort((a,b)=>a-b);
export const mergeLedger=(a,b)=>canonLedger(a.concat(b));
export function ledgerDigest(seed,ledger=[]){let h=mix(seed^0x4c454447);for(let e of canonLedger(ledger))h=mix(h^e);return h>>>0}
export const loopCount=a=>new Set(a.filter(e=>(e&15)==5).map(e=>e>>>24)).size;
export const restoredCount=a=>{let l=loopCount(a);return new Set(a.filter(e=>(e&15)==4&&(e>>>24)==l).map(e=>e>>>16&255)).size};
export const bossDefeated=ledger=>loopCount(ledger)>0;
export function screenState(seed,w,sx,sy,ledger=[]){let n=population(seed,w,sx,sy),dead=new Set,children=new Map,childDead=new Set,well=0,L=loopCount(ledger);for(let raw of ledger){let e=unpack(raw);if(e.sx!=sx||e.sy!=sy)continue;if(e.type==EV.KILL)dead.add(e.subject);if(e.type==EV.BIRTH)children.set(e.subject+':'+e.data,e);if(e.type==EV.CHILD_KILL)childDead.add(e.subject+':'+e.data);if(e.type==EV.WELL&&e.data==L)well=e.subject+1}let mobs=[];for(let i=0;i<n;i++)if(!dead.has(i))mobs.push(species(seed,w,sx,sy,i));for(let [k,e] of children)if(!childDead.has(k)){let gen=e.data>>>4,branch=e.data&15;if(e.subject<n&&gen)mobs.push(descendant(seed,w,sx,sy,e.subject,gen,branch))}return{mobs,well,events:dead.size+children.size+childDead.size}}
export function digest(seed){let w=laws(seed),h=mix(seed);for(let k of ['shape','mut','wet','ruin','agg','magic','bias','sym','eco'])h=mix(h^w[k]);for(let sy=-2;sy<=2;sy++)for(let sx=-2;sx<=2;sx++){let g=region(seed,w,sx,sy);h=mix(h^g.s^g.b^(g.topo<<4)^(g.eco<<8));for(let y=0;y<4;y++)for(let x=0;x<4;x++)h=mix(h^tileAt(seed,w,sx,sy,x,y).q);for(let i=0;i<4;i++)h=mix(h^speciesProgram(seed,w,sx,sy,i).program)}return h>>>0}
export function audit(n=256){let bad=0,seen=new Set;for(let i=0;i<n;i++){let s=mix(0x13c0ffee^Math.imul(i+1,2654435761)),a=digest(s),b=digest(s);if(a!==b)bad++;seen.add(a);let w=laws(s),g=region(s,w,(i%7)-3,(i%5)-2),sp=speciesProgram(s,w,0,0,i%8),t=interpret(sp),d=descendantProgram(s,w,0,0,i%8,1+(i%4),i&15),z=threat(s,w);if(g.ops.length!==6||!Number.isFinite(t.speed)||t.legs<2||t.legs>8||!d.program||!z.program||!Number.isFinite(z.hp))bad++}return{seeds:n,bad,unique:seen.size,pass:bad===0&&seen.size>n*.95}}
