import{mix,Hx,hex,laws,region,tileAt,screenState,descendant,digest,audit,EV,event,unpack,canonLedger,mergeLedger,ledgerDigest,wellSites,restoredCount,loopCount,threat,population}from'./kernel.js';
import{MATS,SCENES,materialAt,scenario,reaction,dungeonAt,dungeonRoom}from'./systems.js';
import{netInit,netToggle,netEvent,netHit,netStep,netPeers,netState}from'./online.js';
const C=document.querySelector('#c'),X=C.getContext('2d'),I=document.querySelector('#info'),S=document.querySelector('#seed'),M=document.querySelector('#modal'),J=document.querySelector('#tip'),O=document.querySelector('#on'),N=document.querySelector('#new'),W=C.width,H=C.height,T=12,SW=27,SH=15,K={};
let seed=Hx(location.hash.slice(1)),world,sites=[],screen={x:0,y:0},mobs=[],shots=[],foe=[],sprouts=[],orbs=[],ledger=[],dun=null,dnode=0,dkey=0,dclear=new Set,dloot=0,note='',noteT=0,panel=-1,AC=0,loopT=0,fx=0,lv=1,xp=0,need=4,up=Array(9).fill(0),pick=[],p={x:160,y:90,hp:8,cd:0,face:0},tick=0,last=performance.now(),acc=0;
const names=['THORN','GLASS','EMBER','MOON','MOSS','ASH','PRISM','VOID','SUN','RAIN','ROOT','FROST'],kinds=['HOPPER','WINKER','STALKER','MAW','BEETLE','MITE','HOUND','MOTE'],DROLE=['ENTRY','KEY','LOCK','SECRET','ROOM','BOSS'],GN=['POWER','RAPID','SPLIT','SEEK','CHAIN','BOUNCE','PHASE','GROW','VITAL'],EN=['','PRISM SWARM','STORM NERVE','GHOST LENS','WORLDROOT','COMET CORE','HIVE NERVE'],GD=['DAMAGE','RATE+SPEED','SPLIT SHOTS','HOMING','CHAIN HIT','WALL BOUNCE','PIERCE+RANGE','SLOW FIELD','MAX HP'],pals=[['#290b18','#ff315e','#ff9db0'],['#311800','#ff7b00','#ffd05a'],['#302b00','#ffe229','#fff2a0'],['#07311c','#20d96b','#9dffc1'],['#071d3d','#2f8fff','#9dc8ff'],['#200a3d','#9b4dff','#ddb7ff'],['#333','#ddd','#fff']],matc=['#2f8fff','#ff5522','#20d96b','#a9e7ff','#b66cff','#58366f'];
const lp=()=>loopCount(ledger),ws=()=>seed^Math.imul(lp(),0x9e3779b9),rg=()=>region(seed,world,screen.x,screen.y),sc=()=>scenario(seed,world,screen.x,screen.y),dr=()=>dun&&dungeonRoom(dun,dnode),palette=b=>pals[b%7],store=()=>`PS${hex(seed)}`,wrap=n=>((n+32)&63)-32,evo=()=>up[3]>3&&up[2]>3?1:up[4]>3&&up[1]>3?2:up[6]>2&&up[3]>2?3:up[7]>3&&up[8]>2?4:up[0]>3&&up[5]>2?5:up[4]>3&&up[3]>3?6:0,cache=()=>event(6,screen.x,screen.y,lp()),zn=()=>names[rg().s%12],well=()=>{for(let s of sites)if(s.x==screen.x&&s.y==screen.y)return s.c;return-1};
function audio(){AC||=new AudioContext}function snd(f){audio();if(!AC)return;let o=AC.createOscillator(),g=AC.createGain(),n=AC.currentTime;o.type='square';o.frequency.value=f;g.gain.setValueAtTime(.06,n);g.gain.exponentialRampToValueAtTime(.001,n+.12);o.connect(g).connect(AC.destination);o.start();o.stop(n+.12)}
onkeydown=e=>{let k=e.key.toLowerCase();audio();if(pick.length&&k>='1'&&k<='3'){choose(+k-1);return}if(pick.length)return;if(panel<0&&(k==' '||k=='enter')){panel=0;return}if(k=='tab'){e.preventDefault();panel=panel?0:-1;return}if(panel)return;K[k]=1;if(k=='e')interact();};onkeyup=e=>K[e.key.toLowerCase()]=0;
function load(){let s=localStorage.getItem(store())||'';ledger=canonLedger(s?s.split('.').map(n=>parseInt(n,36)>>>0):[]);let u=localStorage.getItem(store()+'U');if(u){u=u.split(',').map(Number);lv=u.shift()||1;xp=u.shift()||0;need=u.shift()||4;up=u}}
function save(){localStorage.setItem(store(),ledger.map(n=>n.toString(36)).join('.'));localStorage.setItem(store()+'U',[lv,xp,need,...up])}
function add(e){ledger=canonLedger(ledger.concat(e));save();netEvent(e)}
function init(v=seed){seed=v>>>0;world=laws(seed);screen.x=screen.y=0;p.x=160;p.y=90;p.hp=8;p.cd=0;dun=null;dclear=new Set;dkey=dloot=0;panel=-1;lv=1;xp=0;need=4;up.fill(0);pick=[];tick=0;shots=[];foe=[];sprouts=[];orbs=[];load();sites=wellSites(ws());p.hp=8+up[8];safe();gen();location.hash=hex(seed);S.value=hex(seed);netInit(seed,a=>ledger=mergeLedger(ledger,a),()=>ledger,()=>{save();sites=wellSites(ws());gen()},(g,d)=>{let m=mobs.find(m=>m.g==g);if(m&&!dun){let b=[];hurt(m,d,b,0);mobs=mobs.filter(m=>!m.dead);mobs.push(...b)}})}
function pass(x,y){return dun?x>9&&x<W-9&&y>22&&y<H-9:tileAt(seed,world,screen.x,screen.y,(x/T)|0,(y/T)|0).k!==2}
function mat(x,y){return dun?dr().material:materialAt(seed,world,screen.x,screen.y,(x/T)|0,(y/T)|0).m}
function label(m){m.name=names[m.nameA]+' '+kinds[m.nameB];return m}
function level(){lv++;xp-=need;need=4+lv;let q=mix(seed^Math.imul(lv,31337));pick=[];while(pick.length<3){q=mix(q);let n=q%9;if(!pick.includes(n)&&(n!=2||up[n]<6)&&(n!=3||up[n]<14))pick.push(n)}snd(760)}
function choose(n){let g=pick[n];if(g==null)return;let e=evo();up[g]++;if(g==8)p.hp=Math.min(8+up[8],p.hp+1);let f=evo();pick=[];note=f!=e?'EVOLVED '+EN[f]:GN[g]+' '+up[g];noteT=120;fx=f!=e?8:3;snd(f!=e?1180:980);save();if(xp>=need)level()}
const build=()=>{let e=evo(),b=up.map((v,i)=>v?GN[i].slice(0,4)+v:'').filter(Boolean).join(' ')||'BASE';return(e?EN[e]+' | ':'')+b},res=()=>netPeers(screen.x,screen.y).filter(q=>Math.hypot(q.x-p.x,q.y-p.y)<70).length;
function delta(a,b){return a.wing&&!b.wing?' +WINGS':a.horn&&!b.horn?' +HORN':a.shell&&!b.shell?' +SHELL':a.eye&&!b.eye?' +EYE':a.size>b.size?' +SIZE':a.speed>b.speed+.1?' +SPEED':''}
function hint(){if(panel)return'';if(dun){if(dnode==0&&Math.hypot(p.x-W/2,p.y-H/2)<23)return'E EXIT DUNGEON';if(!mobs.length&&dr().role==3&&!(dloot&1)&&Math.hypot(p.x-W/2,p.y-H/2)<23)return'E CLAIM PRISM CORE';let b=-1,v=1e9;for(let n of dlinks()){let z=dpos(n),q=Math.hypot(p.x-z.x,p.y-z.y);if(q<v)v=q,b=n}if(b>=0&&v<24)return b==dun.lock&&!dkey?'LOCKED - FIND PRISM KEY':'E ENTER '+DROLE[dungeonRoom(dun,b).role];return mobs.length?'CLEAR THE ROOM':''}let c=well();if(c>=0&&Math.hypot(p.x-W/2,p.y-H/2)<25)return mobs.length?'CLEAR ENEMIES - RESTORE WELL':'E RESTORE PRISM WELL';let e=dent();if(e&&Math.hypot(p.x-e.x,p.y-e.y)<25)return mobs.length?'CLEAR ENEMIES - ENTER RUIN':'E ENTER DUNGEON';let q=sc();if(q.type==4&&ledger.includes(cache()))q.type=0;if(q.type>3&&Math.hypot(p.x-q.x,p.y-q.y)<50)return mobs.length?(q.type==4?'CACHE - CLEAR ENEMIES':'RIFT - CLEAR ENEMIES'):q.type==4?'E CLAIM PRISM CACHE':'E TOUCH MUTATION RIFT';return restoredCount(ledger)<7?'FOLLOW BEACON - RESTORE 7 WELLS':'RETURN TO 0,0 - FINAL THREAT'}
function dent(){let d=dungeonAt(seed,world,screen.x,screen.y);return d&&{d,x:40+(d.seed>>>8)%240,y:35+(d.seed>>>16)%105}}
function dlinks(){let a=[];for(let e of dun.edges){if(e[0]==dnode)a.push(e[1]);else if(e[1]==dnode)a.push(e[0])}return a}
function dpos(n){let a=dun.rooms[dnode],b=dun.rooms[n],x=b.x-a.x,y=b.y-a.y;if(Math.abs(x)>=Math.abs(y))return{x:x>0?W-11:11,y:35+n*37%120};return{x:45+n*53%230,y:y>0?H-10:23}}
function gen(){shots=[];foe=[];sprouts=[];orbs=[];if(dun){let q=dr(),r=dun.rooms[dnode],sx=screen.x+r.x,sy=screen.y+r.y;mobs=dclear.has(dnode)?[]:screenState(seed,world,sx,sy,[]).mobs.slice(0,2+(q.scene&1)).map(label);for(let m of mobs)m.dun=1;if(q.role==1&&mobs[0]){mobs[0].guard=1;mobs[0].hp+=2}if(q.role==5&&mobs.length){let m=mobs[0];m.guard=1;m.size=Math.min(4,m.size+2);m.hp+=10+world.agg*2;mobs=[m]}for(let m of mobs){let z=(ledger.length>>3)+lp()*2;m.hp+=z;m.speed+=Math.min(.9,z/20)}return}let full=restoredCount(ledger)==7,boss=full&&screen.x==0&&screen.y==0;mobs=boss?[label(threat(seed,world))]:screenState(seed,world,screen.x,screen.y,ledger).mobs.map(label);let q=sc();if(!boss&&mobs.length){if(q.type==0)for(let m of mobs){m.x=(m.g&1)?24:W-24;m.y=30+((m.g>>>8)%120)}if(q.type==1){let m=mobs[0];m.hp+=q.strength*2;m.size=Math.min(4,m.size+1);m.guard=1}if(q.type==2)for(let m of mobs){m.x=q.x+((m.g&31)-16);m.y=q.y+((m.g>>>5&31)-16)}}if(boss){let m=mobs[0];m.hp+=lp()*12;note='THE PRISM DEVOURER AWAKENS';noteT=180;snd(70)}for(let m of mobs){let L=lp(),z=(ledger.length>>3)+L*2;m.hp+=z;m.speed+=Math.min(.9,z/20);if(!m.boss&&(mix(m.g^L)&31)<=L){m.guard=2;m.size=Math.min(4,m.size+1);m.hp+=4+L*2;if(L>1)m.shoot=1;if(L>2)m.phase|=m.g&1}if(m.boss)m.max=m.hp}}
function restored(c){let s=sites[c];return !!s&&ledger.includes(event(EV.WELL,s.x,s.y,c,lp()))}
function restoreWell(){let c=well(),wx=W/2,wy=H/2+20;if(c<0)return 0;if(restored(c)){note='PRISM WELL ALREADY SINGING';noteT=80;return 1}if(Math.hypot(p.x-wx,p.y-wy)>25){note='APPROACH THE PRISM WELL';noteT=80;return 1}if(mobs.length){note='CLEAR THE PRISM WELL';noteT=80;return 1}add(event(EV.WELL,screen.x,screen.y,c,lp()));p.hp=8+up[8];let n=restoredCount(ledger);note=n==7?'FULL SPECTRUM — RETURN TO SEED 0,0':`PRISM ${c+1} RESTORED  ${n}/7`;noteT=180;snd(n==7?1100:760);return 1}
function interactDungeon(){let q=dr();if(dnode==0&&Math.hypot(p.x-W/2,p.y-H/2)<23){dun=null;dclear=new Set;dkey=dloot=0;p.x=W/2;p.y=H/2+28;safe();gen();note='RETURNED TO THE SURFACE';noteT=100;return}let best=-1,bd=1e9;for(let n of dlinks()){let z=dpos(n),v=Math.hypot(p.x-z.x,p.y-z.y);if(v<bd){bd=v;best=n}}if(best>=0&&bd<24){if(best==dun.lock&&!dkey){note='PRISM LOCK — FIND THE KEY';noteT=100;return}dnode=best;p.x=W/2;p.y=H/2;gen();note=`${DROLE[dr().role]} CHAMBER`;noteT=90;return}if(!mobs.length&&q.role==3&&!(dloot&1)&&Math.hypot(p.x-W/2,p.y-H/2)<23){dloot|=1;xp+=need;save();level();note='SECRET PRISM CORE';noteT=180;return}note='APPROACH A DUNGEON DOOR';noteT=70}
function interactScene(){let q=sc(),e;if(q.type<4)return;if(Math.hypot(p.x-q.x,p.y-q.y)>50){note=q.type==4?'APPROACH PRISM CACHE':'APPROACH THE MUTATION RIFT';noteT=80;return}if(mobs.length){note='CLEAR THE SCENARIO FIRST';noteT=80;return}if(q.type==4){e=cache();if(ledger.includes(e)){note='CACHE EMPTY';noteT=80;return}add(e);xp+=need;save();level();note='PRISM CACHE';noteT=180}else{let n=population(seed,world,screen.x,screen.y),root=q.subject%n,generation=1+Math.min(2,world.mut),branch=q.seed>>>12&15,data=generation<<4|branch;e=event(EV.BIRTH,screen.x,screen.y,root,data);if(ledger.includes(e)){note='THE RIFT IS QUIET';noteT=80}else{add(e);gen();note=`RIFT MUTATION G${generation}`;noteT=150;snd(880)}}}
function interact(){if(dun)return interactDungeon();let e=dent();if(e&&Math.hypot(p.x-e.x,p.y-e.y)<25){if(mobs.length){note='CLEAR THE RUIN ENTRANCE';noteT=90;return}dun=e.d;dnode=dkey=dloot=0;dclear=new Set;p.x=W/2;p.y=H/2+28;gen();note=`DUNGEON GERMINATED — ${dun.n} ROOMS`;noteT=150;return}if(!restoreWell())interactScene()}
function portal(x,y,c=6){X.fillStyle='#000';X.fillRect(x-8,y-10,16,18);X.fillStyle=palette(c)[1];X.fillRect(x-6,y-8,12,16);X.fillStyle='#05050a';X.fillRect(x-3,y-5,6,13);X.fillStyle='#fff';X.fillRect(x-1,y-8,2,2)}
function drawWell(){if(dun)return;let c=well();if(c<0)return;let x=W/2,y=H/2+20,on=restored(c),P=palette(c);X.fillStyle='#000';X.fillRect(x-9,y+6,18,3);X.fillStyle=on?'#fff':P[1];X.fillRect(x-7,y-6,3,13);X.fillRect(x+4,y-6,3,13);X.fillRect(x-4,y-9,8,3);X.fillStyle=P[2];X.fillRect(x-2,y-5,4,9);if(on)for(let i=0;i<7;i++){X.fillStyle=pals[i][1];X.fillRect(x-7+i*2,y-11-(i&1),2,2)}else{X.fillStyle='#fff';X.fillRect(x-1,y-3,2,2)}}
function drawScene(){if(dun)return;let e=dent();if(e)portal(e.x,e.y,rg().b);let q=sc();X.save();X.globalAlpha=.8;X.fillStyle=matc[q.material];if(q.type==3){X.fillRect(q.x-10,q.y-1,21,2);X.fillRect(q.x-1,q.y-10,2,21)}if(q.type==4&&!ledger.includes(cache())){X.fillStyle='#000';X.fillRect(q.x-7,q.y-5,14,10);X.fillStyle=matc[q.material];X.fillRect(q.x-5,q.y-3,10,6);X.fillStyle='#fff';X.fillRect(q.x-1,q.y-4,2,4)}if(q.type==5){X.fillStyle='#fff';X.fillRect(q.x-1,q.y-1,2,2);for(let i=0;i<6;i++){let a=tick/20+i*Math.PI/3;X.fillStyle=matc[q.material];X.fillRect(q.x+Math.cos(a)*9|0,q.y+Math.sin(a)*7|0,2,2)}}X.restore()}
function drawDungeon(){if(!dun)return;let q=dr();for(let n of dlinks()){let z=dpos(n),lock=n==dun.lock&&!dkey;X.fillStyle='#000';X.fillRect(z.x-5,z.y-5,10,10);X.fillStyle=lock?'#f33':n==dun.secret?'#b66cff':matc[dungeonRoom(dun,n).material];X.fillRect(z.x-3,z.y-3,6,6);X.fillStyle='#fff';X.fillRect(z.x-1,z.y-1,2,2)}if(dnode==0)portal(W/2,H/2,dun.b);if(!mobs.length&&q.role==3&&!(dloot&1)){X.fillStyle='#fff';X.fillRect(W/2-2,H/2-2,5,5);X.fillStyle=matc[q.material];X.fillRect(W/2-1,H/2-1,3,3)}}
function bg(){if(dun){let q=dr(),P=palette(dun.b);X.fillStyle='#05050a';X.fillRect(0,0,W,H);X.fillStyle=P[0];X.fillRect(10,22,W-20,H-31);X.fillStyle=matc[q.material];for(let i=0;i<18;i++){let z=mix(q.seed^Math.imul(i+1,31337));X.fillRect(14+z%292,26+(z>>>10)%139,2,2)}X.fillStyle='#000';X.fillRect(0,17,W,5);X.fillRect(0,H-9,W,9);X.fillRect(0,17,9,H);X.fillRect(W-9,17,9,H);return}let g=rg(),P=palette(g.b);for(let y=0;y<SH;y++)for(let x=0;x<SW;x++){let a=tileAt(seed,world,screen.x,screen.y,x,y),m=materialAt(seed,world,screen.x,screen.y,x,y);X.fillStyle=a.k==2?'#101018':P[0];X.fillRect(x*T,y*T,T,T);if(a.k==1){X.fillStyle=P[1];X.fillRect(x*T+((a.q>>8)%8),y*T+((a.q>>12)%8),2,2)}if(a.k==2){let h=5+(g.ruin<<1),v=a.q>>>20&3;X.fillStyle='#080810';X.fillRect(x*T+2,y*T+T-h-1,8,h+1);X.fillStyle=P[2];if(v&1){X.fillRect(x*T+3,y*T+T-h,6,h);X.fillStyle=P[0];X.fillRect(x*T+4,y*T+T-h+2,4,2)}else{X.fillRect(x*T+2,y*T+T-h+2,8,h-2);X.fillRect(x*T+5,y*T+T-h,2,h)}}if((m.q&31)<2){X.fillStyle=matc[m.m];X.fillRect(x*T+(m.q>>>8)%9+1,y*T+(m.q>>>12)%9+1,2,2)}}X.globalAlpha=.07;X.fillStyle=P[1];X.fillRect(0,0,W,H);X.globalAlpha=1}
function sprite(m){let P=palette(m.b),s=m.size,x=m.x|0,y=m.y|0;X.save();X.translate(x,y);X.fillStyle='#000';X.fillRect(-5-s,-5-s,10+s*2,10+s*2);X.fillRect(-5-s,5+s,10+s*2,2);X.fillStyle=P[1];X.fillRect(-4-s,-4-s,8+s*2,8+s*2);X.fillStyle=P[2];X.fillRect(-3-s,-3-s,6+s*2,3+s);X.fillStyle='#111';X.fillRect(-2,-2,1,1);X.fillRect(1,-2,1,1);if(m.eye){X.fillStyle='#fff';X.fillRect(-1,-3,2,2)}if(m.shell){X.fillStyle=P[0];X.fillRect(-3-s,1,6+s*2,3+s)}X.fillStyle=P[1];for(let i=0;i<m.legs;i++){let q=(i/(m.legs-1||1)*(6+s*2)-3-s)|0;X.fillRect(q,4+s,1,3)}if(m.horn){X.fillStyle=P[2];X.fillRect(4+s,-2,3+s,1)}if(m.wing){X.globalAlpha=.65;X.fillRect(-7-s,-2-s,3+s,5+s);X.fillRect(5,-2-s,3+s,5+s);X.globalAlpha=1}if(m.guard){X.strokeStyle='#fff';X.strokeRect(-7-s,-7-s,14+s*2,14+s*2)}if(m.guard>1)for(let i=0;i<3;i++){X.fillStyle=pals[i*2][1];X.fillRect(-3+i*3,-9-s,2,1)}if(m.phase&&tick%20<10){X.globalAlpha=.35;X.fillStyle='#fff';X.fillRect(-5-s,-5-s,10+s*2,10+s*2);X.globalAlpha=1}if(m.f){X.fillStyle='#fff';X.fillRect(-4-s,-4-s,8+s*2,8+s*2);m.f--}if(m.generation){for(let i=0;i<5;i++){X.fillStyle=pals[(m.branch+i)%7][1];X.fillRect(-4+i*2,-8-s-(i&1),1,1)}}if(m.boss){for(let i=0;i<7;i++){let a=tick/18+i*6.28/7;X.fillStyle=pals[i][1];X.fillRect(Math.cos(a)*12|0,Math.sin(a)*9|0,2,2)}}X.restore()}
function peer(q){let P=palette(q.c);X.save();X.translate(q.x|0,q.y|0);X.globalAlpha=.85;X.fillStyle='#000';X.fillRect(-5,-6,10,13);X.fillStyle=P[1];X.fillRect(-4,-5,8,10);X.fillStyle='#fff';X.fillRect(-3,-4,6,3);X.fillStyle='#111';X.fillRect(-2,-3,1,1);X.fillRect(1,-3,1,1);for(let i=0;i<3;i++){X.fillStyle=pals[i*2][1];X.fillRect(-2+i*2,-7-(i&1),1,2)}X.restore()}
function player(){X.save();X.translate(p.x|0,p.y|0);X.fillStyle='#000';X.fillRect(-5,-6,10,12);X.fillRect(-5,6,10,2);X.fillStyle='#eee';X.fillRect(-4,-5,8,10);X.fillStyle='#fff';X.fillRect(-3,-4,6,3);X.fillStyle='#111';X.fillRect(-2,-3,1,1);X.fillRect(1,-3,1,1);for(let i=0;i<7;i++){X.fillStyle=pals[i][1];X.fillRect(-4+i,-7-(i&1),1,2)}X.restore()}
function fire(){if(p.cd)return;snd(420);let e=evo(),a=p.face,sp=3.7+up[1]*.08;shots.push({x:p.x,y:p.y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,t:55+(up[6]+(e==3?2:0))*8,b:6,seek:up[3]+(e==1?2:e==3||e==6?2:0),bounce:up[5]+(e==5?2:0),split:up[2]+(e==1),chain:up[4]+(e==6?2:0),phase:up[6]+(e==3?2:0),grow:up[7]+(e==4?2:0),power:1+up[0]+res()+(e==2||e==5?2:0)});p.cd=Math.max(2,9-up[1]-(e==2))}
function safe(){if(pass(p.x,p.y))return;let a,b,d=1e9;for(let y=26;y<H-9;y+=T)for(let x=10;x<W-9;x+=T)if(pass(x,y)){let q=Math.abs(x-p.x)+Math.abs(y-p.y);if(q<d)d=q,a=x,b=y}p.x=a||W/2;p.y=b||H/2}
function input(){let dx=(K.d||K.arrowright?1:0)-(K.a||K.arrowleft?1:0),dy=(K.s||K.arrowdown?1:0)-(K.w||K.arrowup?1:0);if(dx||dy){let d=Math.hypot(dx,dy),nx=p.x+dx/d*1.6,ny=p.y+dy/d*1.6;p.face=Math.atan2(dy,dx);if(pass(nx,ny)){p.x=nx;p.y=ny}}if(K[' ']||K.enter)fire();if(p.cd)p.cd--;if(dun)return;let changed=0;if(p.x<0){screen.x=wrap(screen.x-1);p.x=W-2;changed=1}if(p.x>W){screen.x=wrap(screen.x+1);p.x=2;changed=1}if(p.y<18){screen.y=wrap(screen.y-1);p.y=H-2;changed=1}if(p.y>H){screen.y=wrap(screen.y+1);p.y=20;changed=1}if(changed){safe();gen()}}
function birthsHere(){let n=0;for(let q of ledger){let e=unpack(q);if(e.type==EV.BIRTH&&e.sx==screen.x&&e.sy==screen.y)n++}return n}
function die(m,born){orbs.push({x:m.x,y:m.y,v:1+(m.guard?2:0)+(m.boss?5:0)});if(m.dun)return;if(m.boss){let l=lp();add(event(EV.BOSS,0,0,0,l));loopT=1;note='PRISM LOOP '+(l+2)+' — WORLD ESCALATES';noteT=300;fx=8;snd(1320);return}let data=m.generation<<4|m.branch;add(event(m.generation?EV.CHILD_KILL:EV.KILL,screen.x,screen.y,m.root,data));let h=ledgerDigest(seed,ledger),roll=mix(m.g^h^0x42524954)&255,limit=28+world.mut*42;if(roll<limit&&birthsHere()<12){let generation=Math.min(15,(m.generation||0)+1),branch=m.generation?m.branch:mix(m.g^h)>>>8&15,b=generation<<4|branch,e=event(EV.BIRTH,screen.x,screen.y,m.root,b);if(!ledger.includes(e)){add(e);let c=label(descendant(seed,world,screen.x,screen.y,m.root,generation,branch));c.x=m.x;c.y=m.y;born.push(c);note=`MUTATION ${c.name} G${generation}${delta(c,m)}`;noteT=180;snd(880)}}else{note=`EXTINCT LINE: ${m.name}`;noteT=80}}
function hurt(m,d,born,n=1){if(m.dead)return;if(n&&!m.dun)netHit(m.g,d);m.hp-=d;m.f=2;snd(150);if(m.hp<=0){m.dead=1;die(m,born)}}
function hit(){p.hp--;fx=-4}function ai(m){let dx=p.x-m.x,dy=p.y-m.y,d=Math.hypot(dx,dy)||1;m.t++;if(m.behavior==1&&m.t%70>45){m.vx=dx/d*2.1;m.vy=dy/d*2.1}else if(m.behavior==2){m.vx=Math.cos((m.t+(m.g&31))/18)*.7-dy/d*.2;m.vy=Math.sin((m.t+(m.g&31))/18)*.7+dx/d*.2}else{let z=mix(m.g^Math.imul(m.t,1597334677));m.vx+=((z&255)/255-.5)*.04;m.vy+=(((z>>>8)&255)/255-.5)*.04;if(d<85){m.vx+=dx/d*.025;m.vy+=dy/d*.025}}if(m.shoot&&m.t%90==(m.g&31)%30)foe.push({x:m.x,y:m.y,vx:dx/d*1.7,vy:dy/d*1.7,t:90,b:m.b});if(m.boss&&m.t%48==0)for(let i=0;i<8;i++){let a=i*Math.PI/4+m.t/80;foe.push({x:m.x,y:m.y,vx:Math.cos(a)*1.5,vy:Math.sin(a)*1.5,t:95,b:i%7})}let v=Math.hypot(m.vx,m.vy)||1,lim=m.speed+(m.wing?.25:0);if(sprouts.some(s=>Math.hypot(s.x-m.x,s.y-m.y)<12))lim*=.55;if(v>lim){m.vx=m.vx/v*lim;m.vy=m.vy/v*lim}let nx=m.x+m.vx,ny=m.y+m.vy;if(m.wing||m.phase||pass(nx,ny)){m.x=nx;m.y=ny}else m.vx=m.vy=0;m.x=Math.max(10,Math.min(310,m.x));m.y=Math.max(28,Math.min(170,m.y));if(d<7+m.size&&tick%30==0)hit()}
function reset(all){if(all){if(netState()[2])netToggle();ledger=[];localStorage.removeItem(store())}localStorage.removeItem(store()+'U');lv=1;xp=0;need=4;up.fill(0);pick=[];dun=null;screen.x=screen.y=0;p.x=W/2;p.y=H/2;p.hp=8;sites=wellSites(ws());safe();gen();save();note=all?'WORLD RESET':'PRISM SHATTERED — BUILD RESET';noteT=180}function prismDeath(){reset()}
function update(){if(panel||pick.length){if(panel>0)panel--;tick++;return}input();if(!dun)netStep(performance.now(),screen.x,screen.y,p.x,p.y);for(let m of mobs)ai(m);let born=[],spawn=[];for(let s of shots){if(s.seek&&mobs.length){let m=mobs.reduce((a,b)=>Math.hypot(b.x-s.x,b.y-s.y)<Math.hypot(a.x-s.x,a.y-s.y)?b:a,mobs[0]),a=Math.atan2(m.y-s.y,m.x-s.x),v=Math.hypot(s.vx,s.vy);let h=Math.min(.75,.06*s.seek),vx=s.vx*(1-h)+Math.cos(a)*v*h,vy=s.vy*(1-h)+Math.sin(a)*v*h,d=Math.hypot(vx,vy)||v;s.vx=vx/d*v;s.vy=vy/d*v}s.x+=s.vx;s.y+=s.vy;s.t--;if(!s.phase&&!pass(s.x,s.y)){if(s.bounce){s.vx=-s.vx;s.vy=-s.vy;s.bounce--}else s.t=0}for(let m of mobs)if(!m.dead&&m.hp>0&&Math.hypot(s.x-m.x,s.y-m.y)<6+m.size){let r=reaction(s.b,mat(m.x,m.y)),d=s.power+(r==1);hurt(m,d,born);if(r==3)p.hp=Math.min(8+up[8],p.hp+1);if(s.chain||r==2){let o=mobs.find(o=>o!==m&&!o.dead&&Math.hypot(o.x-m.x,o.y-m.y)<55);if(o)hurt(o,1+(s.chain>>1),born)}if(s.grow)sprouts.push({x:m.x,y:m.y,t:120+s.grow*60});if(s.split){for(let i=0,n=Math.min(6,s.split);i<n;i++){let z=(i-(n-1)/2)*.28,a=Math.atan2(s.vy,s.vx)+z,v=Math.hypot(s.vx,s.vy);spawn.push({...s,x:s.x,y:s.y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,t:32,split:0})}}s.t=0;break}}shots.push(...spawn);for(let s of foe){s.x+=s.vx;s.y+=s.vy;s.t--;if(Math.hypot(s.x-p.x,s.y-p.y)<5){hit();s.t=0}}if(!dun){let q=sc();if(q.type==3&&tick%30==0&&Math.hypot(p.x-q.x,p.y-q.y)<12+q.strength*2)hit()}mobs=mobs.filter(m=>!m.dead);mobs.push(...born);for(let o of orbs){let dx=p.x-o.x,dy=p.y-o.y,d=Math.hypot(dx,dy)||1;if(d<45){o.x+=dx/d*1.8;o.y+=dy/d*1.8}if(d<8){xp+=o.v*(1+res());o.dead=1;fx=2;snd(620);save()}}orbs=orbs.filter(o=>!o.dead);if(!pick.length&&xp>=need)level();if(dun&&!mobs.length&&!dclear.has(dnode)){dclear.add(dnode);let q=dr();if(q.role==1){dkey=1;note='PRISM KEY CLAIMED';noteT=120}if(q.role==5&&!(dloot&2)){dloot|=2;xp+=need;save();level();note='GUARDIAN PRISM CORE';noteT=200;snd(1080)}}shots=shots.filter(s=>s.t>0&&s.x>0&&s.x<W&&s.y>18&&s.y<H);foe=foe.filter(s=>s.t>0&&s.x>0&&s.x<W&&s.y>18&&s.y<H);sprouts=sprouts.filter(s=>--s.t>0);if(p.hp<=0)prismDeath();if(loopT){loopT=0;sites=wellSites(ws());p.hp=8+up[8];gen()}if(noteT)noteT--;tick++}
function codex(){if(panel)M.textContent=`PRISMSEED: THE LIVING CARTRIDGE

KILL → PRISM XP → CHOOSE UPGRADES.
RESTORE 7 WELLS. RETURN 0,0. BEAT BOSS. LOOP HARDER.
DEATH RESETS BUILD. NEW RESETS THIS WORLD.
ONLINE: SAME SEED = SAME WORLD.

WASD MOVE   SPACE/CLICK SHOOT
E USE   SPACE/CLICK PLAY   TAB HELP`;else if(pick.length){let a='<b>LEVEL '+lv+' — CHOOSE AN UPGRADE</b><br>';for(let i=0;i<3;i++){let g=pick[i],e=evo();up[g]++;let f=evo();up[g]--;a+='<button data-u='+i+'><b>'+(i+1)+' '+GN[g]+'</b><br>'+GD[g]+'<br>'+up[g]+' → '+(up[g]+1)+(f!=e?'<br>★ '+EN[f]:'')+'</button>'}M.innerHTML=a}else M.textContent=''}
function draw(){bg();drawWell();drawScene();drawDungeon();for(let s of sprouts){X.fillStyle=matc[2];X.fillRect(s.x-2,s.y-2,4,4)}for(let o of orbs){X.fillStyle='#fff';X.fillRect(o.x-2,o.y,5,1);X.fillRect(o.x,o.y-2,1,5);X.fillStyle=pals[(o.v+lv)%7][1];X.fillRect(o.x-1,o.y-1,3,3)}for(let s of shots){X.fillStyle=palette(s.b)[2];X.fillRect(s.x-1,s.y-1,3,3)}for(let s of foe){X.fillStyle=palette(s.b)[2];X.fillRect(s.x-1,s.y-1,3,3)}for(let m of mobs)sprite(m);let B=mobs.find(m=>m.boss);if(B){X.fillStyle='#000';X.fillRect(79,20,162,5);X.fillStyle='#f33';X.fillRect(81,22,158*B.hp/B.max,2)}if(!dun)for(let q of netPeers(screen.x,screen.y))peer(q);player();if(fx){X.strokeStyle=fx<0?'#f33':'#fff';X.strokeRect(1,18,W-2,H-20);fx+=fx<0?1:-1}X.fillStyle='#000a';X.fillRect(0,0,W,17);let wc=restoredCount(ledger),L=lp();if(dun){let q=dr();I.innerHTML=`LOOP ${L+1} | ZONE ${screen.x},${screen.y} | LV ${lv} XP ${xp}/${need} | HP ${p.hp}/${8+up[8]} | DUNGEON ${dnode+1}/${dun.n} ${DROLE[q.role]}<br>BUILD ${build()}`}else{let next=sites.find(s=>!restored(s.c)),goal=next?'> '+next.x+','+next.y:'> 0,0';if(next&&(next.x!=screen.x||next.y!=screen.y)){let a=Math.atan2(next.y-screen.y,next.x-screen.x),gx=W/2+Math.cos(a)*(W/2-7),gy=H/2+Math.sin(a)*(H/2-24);X.fillStyle='#000';X.fillRect(gx-3,gy-3,7,7);X.fillStyle=pals[next.c][1];X.fillRect(gx-2,gy-2,5,5);X.fillStyle='#fff';X.fillRect(gx,gy,1,1)}let ns=netState();let here=netPeers(screen.x,screen.y).length,st=ns[0]>0?'ONLINE '+ns[1]+' HERE '+here:ns[0]<0?'NET ERROR':ns[2]?'CONNECTING':'OFFLINE';I.innerHTML=`LOOP ${L+1} | ZONE ${screen.x},${screen.y} ${zn()} | LV ${lv} XP ${xp}/${need} | HP ${p.hp}/${8+up[8]} | WELLS ${wc}/7 | GO ${goal.slice(2)} | ${st}`+(res()?' | RES '+res():'')+'<br>BUILD '+build();O.textContent=ns[0]>0?'ONLINE '+ns[1]:ns[0]<0?'RETRY':ns[2]?'CONNECTING':'ONLINE'}codex();J.textContent=noteT?note:hint()}
function loop(now){acc=Math.min(100,acc+now-last);last=now;while(acc>=1000/60){update();acc-=1000/60}draw();requestAnimationFrame(loop)}
M.onclick=e=>{audio();let b=e.target.closest('button');if(b&&pick.length){choose(+b.dataset.u);return}if(panel)panel=0};O.onclick=()=>{audio();netToggle();snd(660)};N.onclick=()=>confirm('ERASE THIS WORLD?')&&reset(1);S.onchange=()=>init(Hx(S.value));C.onpointerdown=e=>{audio();let r=C.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;if(panel){panel=0;return}if(pick.length)return;p.face=Math.atan2(y-p.y,x-p.x);fire()};window.prismAudit=audit;window.prismLoop=()=>lp();window.prismEvo=()=>evo();window.prismDigest=()=>hex(digest(seed));window.prismLedger=()=>({hash:hex(ledgerDigest(seed,ledger)),raw:[...ledger],events:ledger.map(unpack)});window.prismMobs=()=>mobs.map(m=>[m.g,m.hp,m.x,m.y,m.f||0]);window.prismState=()=>[lv,xp,lp(),...up];window.prismZone=zn;window.prismElites=()=>mobs.filter(m=>m.guard>1).length;window.prismSetBuild=a=>{up=a};window.prismBoss=()=>{let m=mobs.find(m=>m.boss);return m&&[m.hp,m.max]};window.prismStep=update;window.prismKill=()=>p.hp=0;window.prismHit=hit;window.prismFx=()=>fx;window.prismPush=()=>mobs.forEach(m=>{m.x=-99;m.y=999});window.prismWarp=(a,b,x,y)=>{screen.x=a;screen.y=b;p.x=x;p.y=y;gen()};window.prismClear=()=>mobs=[];window.prismUse=interact;window.prismChoose=choose;window.prismMerge=a=>{ledger=mergeLedger(ledger,a||[]);save();sites=wellSites(ws());gen();return window.prismLedger()};
init(seed);requestAnimationFrame(loop);